#!/bin/bash

TRAP() {
echo "Please wait for the operation to complete..."
}

FindDate() {
YEAR=$(date +%Y -r ${1})
MONTH=$(date +%B -r ${1})
DAY=$(date +%d -r ${1})
}

# Function to check if a directory exists before attempting to create one:
CheckDir() {
if [[ ! -d ${FileDir} ]]; then
  mkdir -p ${FileDir}
fi
}

# Function to check if a file already exist before attempting to move/copy it:
CheckFile() {
if [[ -f ${FileDir}/${FILE} ]]; then
  echo "File with name '${FILE}' already exists in '${FileDir}'; skipping..."
  continue
fi
}

CopyFile() {
CheckFile
cp ${1} ${FileDir}
}

MoveFile() {
CheckFile
mv ${1} ${FileDir}
}
