#!/bin/bash
# Lab Objective: Start building a function library.
#
# Pre-req: copy and extract /var/share/CS225/timefiles.tar.gz to your home directory.
#
# Create a script that:
# - looks at the modified timestamp of each file in timefiles
# - creates a directory structure for the month and day in timefiles directory
# - copies each file to the appropriate directory
# - moves each file to the appropriate directory if -f (force) is set
#
# Script has to include the following
# - syntax/help function
# - getopts options 
# - trap for control-c
# - function library for generic functions (check timestamp, create directory, print syntax etc..)
# - uses pattern substitution
#
# What to turn in:
# - lab11.sh
# - functionLibrary.sh

# Linking function library:
. ./FunctionLibrary

# Processing arguments:
while getopts :fh OPT; do
  case "$OPT" in
    f) FORCE="YES";;
    h) HELP="WANTED";;
    *) echo "Unknown argument detected. Please run ${0##*/} -h for correct usage information.";;
  esac
done

# Processing -h option:
if [ ! -z $HELP ]; then
  echo "This script is designed to create a directory structure based on modified timestamp of all files in a directory."
  echo "Usage:"
  echo " ${0##*/} DIRECTORY		Creates a Month/Day structure inside of a DIRECTORY and copies files accordingly"
  echo " ${0##*/} -f DIRECTORY		Creates a Month/Day structure inside of a DIRECTORY and MOVES files accordingly"
  echo " ${0##*/} -h			Prints this message and exits"
  exit
fi

# Removing options, keeping additional arguments:
shift $[ $OPTIND - 1 ]

DIRECTORY=${1}
FILELIST=${DIRECTORY}/*

for LINE in ${FILELIST}; do
echo "$LINE"
  FindDate ${LINE}
  FileDir="${DIRECTORY}/${YEAR}/${MONTH}/${DAY}"
  CheckDir
  if [[ -z ${FORCE} ]]
    then
     CopyFile 
    else
     MoveFile
  fi
sleep 0.1
done



