#!/bin/bash
#
# Lab Objective: Create a script with four functions using BASH's in process
# regular expressions to check the validity of Social Security numbers, telephone
# numbers, IP addresses and credit card numbers based on each particular data format.
#
# Take a piece of data as an argument and echo back it's type based on the results of these functions.
# - Each function will be named check_ip, check_ssn, check_pn and check_ccn.
# - Each function will take one argument - the data in question
# - Each function will return a message and a 1 or 0 depending on the outcome of the comparison
# - Make sure the script traps control-c and exits
# - Make sure the script prints out help if no argument is given.

# Trapping the CTRL+C:
TRAP() {
echo "    OK, exiting..."
exit 130
}
trap "TRAP" SIGINT

# Checking if input parameter has been supplied and providing help messages if needed:
if [ -z "$1" ]
  then
    echo "Numerical input expected. The following are correct usage scenarios:"
    echo "    ${0##*/} 123-45-6789		Checks validity of a Social Security number;"
    echo "    ${0##*/} (123) 456-7890	Checks validity of a telephone number;"
    echo "    ${0##*/} 1.23.134.245		Checks validity of an IP address;"
    echo "    ${0##*/} 1234567890987654	Checks validity of a credit card number."
    exit 123
fi

# Functions:
check_ip()
{
if [[ "$1" =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$ ]]
  then return 0
  else return 1
fi
}

check_ssn()
{
if [[ "$1" =~ ^[0-9]{3}(| |-|\.)?[0-9]{2}(| |-|\.)?[0-9]{4}$ ]]
  then return 0
  else return 1
fi
}

check_pn()
{
if [[ "$1" =~ ^(\+?[0-9]{1-3}(| |-|\.)?)?[\(]?[0-9]{3}[\)]?(| |-|\.)?[0-9]{3}(| |-|\.)[0-9]{4}$ ]]
  then
    return 0
  else
    return 1
fi
}

check_ccn()
{
# AmEx CCNs begin with "37" or "34"; Visa - "4," MasterCard - "5;" Discover - "6."
# AmEx CCNs are 15-digit long, in three blocks of 4, 6 and 5 digits.
# http://blog.unibulmerchantservices.com/10-signs-of-a-valid-american-express-card/
if [[ "$1" =~ ^[3-6][0-9]{3}(| |\.|-)?[0-9]{4}(((| |\.|-)?[0-9]{4}){2}|[0-9]{2}(| |\.|-)?[0-9]{5})$ ]]
  then return 0
  else return 1
fi
}

# Assigning input to a TEMP variable:
TEMP="$@"

if $(check_ip "$TEMP")
  then
    echo "$TEMP is a valid IP address."
  elif $(check_ssn "$TEMP")
    then
      echo "$TEMP is a valid Social Security number."
    elif $(check_pn "$TEMP")
      then
        echo "$TEMP is a valid telephone number."
      elif $(check_ccn "$TEMP")
        then
          echo "$TEMP is a valid Credit Card number."
        else
          echo "Unable to determine the type of input; please try again..."
fi
