#!/bin/bash
#
# Lab Objective: Create a script with four functions using BASH's in process
# regular expressions to check the validity of Social Security numbers, telephone
# numbers, IP addresses and credit card numbers based on each particular data format.
#
# Take a piece of data as an argument and echo back it's type based on the results of these functions.
# - Each function will be named check_ip, check_ssn, check_pn and check_ccn.
# - Each function will take one argument - the data in question
# - Each function will return a message and a 1 or 0 depending on the outcome of the comparison
# - Make sure the script traps control-c and exits
# - Make sure the script prints out help if no argument is given.

# Linking function library file:
. ~/bin/FunctionLibrary.lab13

# Trapping CTRL+C:
trap "TRAP" SIGINT

# Checking if input parameter has been supplied and providing help messages if needed:
if [ -z "$1" ]
  then
    echo "Numerical input expected. The following are correct usage scenarios:"
    echo "    ${0##*/} 123-45-6789           Checks validity of a Social Security number;"
    echo "    ${0##*/} [+1] 123-456-7890     Checks validity of a telephone number;"
    echo "    ${0##*/} 1.23.134.245          Checks validity of an IP address;"
    echo "    ${0##*/} 4123456789098765      Checks validity of a credit card number."
    exit 123
fi

# Assigning input to a TEMP variable:
TEMP="$@"

if $(check_ip "$TEMP")
  then
    echo "$TEMP is a valid IP address."
  elif $(check_ssn "$TEMP")
    then
      echo "$TEMP is a valid Social Security number."
    elif $(check_pn "$TEMP")
      then
        echo "$TEMP is a valid telephone number."
      elif $(check_ccn "$TEMP")
        then
          echo "$TEMP is a valid Credit Card number."
        else
          echo "Unable to determine the type of input... For help run ${0##*/} without arguments and try again."
fi
