#!/bin/bash
# Lab Objective: Start building a function library.
#
# Pre-req: copy and extract /var/share/CS225/timefiles.tar.gz to your home directory.
#
# Create a script that:
# - looks at the modified timestamp of each file in timefiles
# - creates a directory structure for the month and day in timefiles directory
# - copies each file to the appropriate directory
# - moves each file to the appropriate directory if -f (force) is set
#
# Script has to include the following
# - syntax/help function
# - getopts options 
# - trap for control-c
# - function library for generic functions (check timestamp, create directory, print syntax etc..)
# - uses pattern substitution
#
# What to turn in:
# - lab11.sh
# - functionLibrary.sh

# Trapping the CTRL+C:
trap "TRAP" SIGINT

# Linking function library:
. ./FunctionLibrary

# Processing arguments:
while getopts :fh OPT; do
  case "$OPT" in
    f) FORCE="YES";;
    h) HELP="WANTED";;
    *) echo "Unknown argument detected. Please run ${0##*/} -h for correct usage information."; exit;;
  esac
done

# Processing -h option:
if [ ! -z $HELP ]; then
  echo -e "This script is designed to create a Year/Month/Day structure inside of a DIRECTORY based on \nthe modified time of all the files in the DIRECTORY, and copy/move files accordingly."
  echo "Usage:"
  echo "	${0##*/} DIRECTORY			Creates the Year/Month/Day structure and copies all the files"
  echo "	${0##*/} -f DIRECTORY		Creates the Year/Month/Day structure and moves all the files"
  echo "	${0##*/} -h			Prints this message and exits"
  exit
fi

# Removing options, keeping additional arguments:
shift $[ ${OPTIND} - 1 ]

DIR="${1}"
FILELIST="$DIR/*"
for LINE in ${FILELIST}; do
FILE="${LINE##*/}"
echo "Processing file ${FILE}"
if [[ ( -d ${LINE} ) && ( ! -L ${LINE} ) ]]
  then
    echo "${FILE} is a directory, skipping..."
  else
    FindDate ${LINE}
    FileDir=${DIR}/${YEAR}/${MONTH}/${DAY}
    CheckDir
    if [[ -z ${FORCE} ]]
      then
        CopyFile ${LINE}
      else
        MoveFile ${LINE}
    fi
fi
done
