#!/bin/bash
#
# Lab Objective: Use logical ANDs and ORs in conditions to simplify your code.
# Prompt the user for a number, sanitize the input (eg make sure the input is an integer)
# and using a logical AND to ensure it's between 50 and 100.
# Do this with ONE if conditional. 
#
# Prompt the user for an integer
# Ensure it's an integer
# Check to see if it's in the desired range (50-100)
# Let the user know if it's a success
#
#
clear
echo
read -r -p "Please enter a whole number between 50 and 100: " INPUT 
INPUT=$((10#$INPUT))
if [[ "$INPUT" -eq "$INPUT" ]] && (( "$INPUT" <= 100 & "$INPUT" >= 50 )) 2>/dev/null
  then
    echo "Success!"
  else
    echo "Hmm... Your input is either not a whole number or is out of range."
fi
echo
