#!/bin/bash
#
# Lab Objective: Create a script called lab6.sh that will check to see if each media file in the medialab directory is in medialab/media.xml
#
# List the filenames in the medialab directory that are not in media.xml
# Display the number of files in the medialab directory that are not in media.xml
# List the media files by name in media.xml that do not exist in the medialab directory
# Display the number of files that are in the media.xml that do not exist in the medialab directory
#
# Desired Output:
#
# Files not in media.xml:
# file1.mpg
# file2.mpg
# file3.mpg
# Files not in medialab directory:
# file4.mpg
# file5.mpg
# file6.mpg
# 3 media files in medialab directory that are NOT listed in media.xml
# 3 media files in media.xml that are NOT in medialab directory


# Changing field separator so filenames with spaces translated properly:
OldIFS=#IFS
IFS=$'\n'

# Saving all filenames in the medialab directory to a temp file:
ls -1 medialab > file.tmp

# Cleaning the XML file and generating an array with all the filenames in the XML file:
grep filename < medialab/media.xml | awk -F'[<|>]' '{print $3}' | sort | uniq > xml.tmp

# Using comm to compare files:
echo "Files not in media.xml:"
comm -23 file.tmp xml.tmp
echo " Files not in medialab directory:"
comm -13 file.tmp xml.tmp
echo
echo "`comm -23 file.tmp xml.tmp | wc -l` media files in medialab directory that are NOT listed in media.xml"
echo "`comm -13 file.tmp xml.tmp | wc -l` media files in media.xml that are NOT in medialab directory"
echo

# Cleaning up:
IFS=$OldIFS
exit
rm -f file.tmp
rm -f xml.tmp
