#!/bin/bash
#
# Lab Objective: Create a script called lab6.sh that will check to see if each media file in the medialab directory is in medialab/media.xml
#
# List the filenames in the medialab directory that are not in media.xml
# Display the number of files in the medialab directory that are not in media.xml
# List the media files by name in media.xml that do not exist in the medialab directory
# Display the number of files that are in the media.xml that do not exist in the medialab directory
# 
# Desired Output:
# 
# Files not in media.xml:
# file1.mpg
# file2.mpg
# file3.mpg
# Files not in medialab directory:
# file4.mpg
# file5.mpg
# file6.mpg
# 3 media files in medialab directory that are NOT listed in media.xml
# 3 media files in media.xml that are NOT in medialab directory


# Changing field separator so filenames with spaces translate properly:
OldIFS=#IFS
IFS=$'\n'

# Saving all the filenames in the medialab directory to a temp file:
ls -1 medialab > file.tmp

# Saving all the filenames from the XML file to a temp file:
grep filename < medialab/media.xml | awk -F'[<|>]' '{print $3}' | sort -r | uniq > xml.tmp

# Checking if files with filenames from XML file exist and creating a common list;
# Using while loop to read file due to reasons described here: http://mywiki.wooledge.org/DontReadLinesWithFor
# Style credits: http://stackoverflow.com/a/1521498
while read LINE; do
  if [[ -f medialab/$LINE ]]
    then
      echo $LINE >> CommonList.tmp
  fi
done < xml.tmp

# Adding the common list to both temp files to prepare for awk processing:
cat CommonList.tmp >> file.tmp
cat CommonList.tmp >> xml.tmp

# Generating the output. Awk eliminates duplicates and outputs only unique values.
# Credits: http://stackoverflow.com/a/23740629
echo "Files not in media.xml:"
awk '{!seen[$0]++};END{for(i in seen) if(seen[i]==1)print i}' file.tmp > ufile.tmp
# ^ Sending the awk output to another temp file to simplify file count below.
cat ufile.tmp
echo
echo "Files not in medialab directory:"
awk '{!seen[$0]++};END{for(i in seen) if(seen[i]==1)print i}' xml.tmp | grep -ve '^$' > uxml.tmp
# ^ The last grep above removes an empty line; credits: http://stackoverflow.com/a/3432574
cat uxml.tmp
echo
echo "$(wc -l < ufile.tmp) media files in medialab directory that are NOT listed in media.xml"
echo "$(wc -l < uxml.tmp) media files in media.xml that are NOT in medialab directory"

# Cleaning up:
IFS=$OldIFS
rm -f file.tmp
rm -f ufile.tmp
rm -f xml.tmp
rm -f uxml.tmp
rm -f CommonList.tmp
echo
