#!/bin/bash
#
# Lab Objective: Create a script called lab6.sh that will check to see if each media file in the medialab directory is in medialab/media.xml
#
# List the filenames in the medialab directory that are not in media.xml
# Display the number of files in the medialab directory that are not in media.xml
# List the media files by name in media.xml that do not exist in the medialab directory
# Display the number of files that are in the media.xml that do not exist in the medialab directory
# 
# Desired Output:
# 
# Files not in media.xml:
# file1.mpg
# file2.mpg
# file3.mpg
# Files not in medialab directory:
# file4.mpg
# file5.mpg
# file6.mpg
# 3 media files in medialab directory that are NOT listed in media.xml
# 3 media files in media.xml that are NOT in medialab directory
#
#
# Changing field separator so filenames with spaces translated properly:
OldIFS=#IFS
IFS=$'\n'
#
# Generating an array with all filenames in the medialab directory:
FILEARRAY=(`ls medialab | grep -vE "media"`)
# Saving an array to a temp file for a later processing;
printf '%s\n' "${FILEARRAY[@]}" > file.tmp
#
# Cleaning the XML file and generating an array with all the filenames in the XML file:
XMLARRAY=(`grep filename < medialab/media.xml | awk -F'[<|>]' '{print $3}' | sort | uniq | grep -vwE "NULL"`)
# Saving an array to a temp file for a later processing;
printf '%s\n' "${XMLARRAY[@]}" > xml.tmp
#
# Comparing the two arrays and creating a common list;
# In the future may get rid of slow nested for loops and use awk:
for EXTVAR in "${XMLARRAY[@]}"; do
  for INTVAR in "${FILEARRAY[@]}"; do
    if [ "$EXTVAR" == "$INTVAR" ]
      then
        COMMONLIST=("${COMMONLIST[@]}" "$INTVAR")
        break
    fi
  done
done
#
# Adding the common list to both temp files to prepare for awk processing:
printf '%s\n' "${COMMONLIST[@]}" >> file.tmp
printf '%s\n' "${COMMONLIST[@]}" >> xml.tmp
#
# Generating the output. Awk eliminates duplicates and outputs only unique values; credits:
# http://stackoverflow.com/questions/23740545/how-to-print-only-the-unique-lines-in-bash
echo "Files not in media.xml:"
awk '{!seen[$0]++};END{for(i in seen) if(seen[i]==1)print i}' file.tmp > xml.uniq
# ^ Sending the awk output to another temp file to simplify file count below; need to fix that...
cat xml.uniq
echo
echo "Files not in medialab directory:"
awk '{!seen[$0]++};END{for(i in seen) if(seen[i]==1)print i}' xml.tmp > file.uniq
cat file.uniq
echo
echo "`wc -l < xml.uniq` media files in medialab directory that are NOT listed in media.xml"
echo "`wc -l < file.uniq` media files in media.xml that are NOT in medialab directory"
#
#
# Cleaning up:
IFS=$OldIFS
rm -f file.tmp
rm -f file.uniq
rm -f xml.tmp
rm -f xml.uniq
echo
