#!/bin/bash
# Lab Objective: Using the last line of /var/share/CS225/addresses.csv gather each field
# into the following variables using bash pattern substitution. Do NOT use awk for this!
#
# FNAME
# LNAME
# COMPANY
# STREET
# CITY
# STATE
# ZIP
# HPHONE
# WPHONE
# EMAIL
# WEBURL
#
# Sample line from the addresses.csv file (note comma in the third field):
# "Jeri","Farstvedt","Regan, Denis J Esq","16133 Ventura Blvd #-700","Encino","Los Angeles","CA","91436","818-986-8843","818-986-6786","jeri@farstvedt.com","http://www.jerifarstvedt.com"

if [ -z "$1" ]					# Checking if input parameter has been supplied.
  then
    echo "Usage:"
    echo "${0##*/} /var/share/CS225/addresses.csv"
    exit 123
  elif [ ! -f $1 ]				# Checking if supplied parameter is a file.
    then
      echo "Usage:"
      echo "${0##*/} /var/share/CS225/addresses.csv"
      echo
      echo "Cannot open "$1" for reading; exiting..."
      exit 403
fi

VAR1=$(tac $1|grep --max-count=1 .)		# Getting the last non-empty line from the input file into a temp variable; credits: http://stackoverflow.com/a/2639060
VAR1=${VAR1#\"}; VAR1=${VAR1%\"}		# Removing fist and last " from the input
FNAME=${VAR1%%\",\"*}				# Copying the first field to a new variable.
VAR1=${VAR1#*\",\"}				# Removing the first field from temp variable.
LNAME=${VAR1%%\",\"*}				# Copying the first of remaining fields to a new variable.
VAR1=${VAR1#*\",\"}				# Removing the first of remaining fields from a temp variable.
COMPANY=${VAR1%%\",\"*}
VAR1=${VAR1#*\",\"}
STREET=${VAR1%%\",\"*}
VAR1=${VAR1#*\",\"}
CITY=${VAR1%%\",\"*}
VAR1=${VAR1#*\",\"}; VAR1=${VAR1#*\",\"}	# Removing first field twice since County field is not needed.
STATE=${VAR1%%\",\"*}
VAR1=${VAR1#*\",\"}
ZIP=${VAR1%%\",\"*}
VAR1=${VAR1#*\",\"}
HPHONE=${VAR1%%\",\"*}
VAR1=${VAR1#*\",\"}
WPHONE=${VAR1%%\",\"*}
VAR1=${VAR1#*\",\"}
EMAIL=${VAR1%%\",\"*}
VAR1=${VAR1#*\",\"}
WEBURL=${VAR1%%\",\"*}
echo "First Name:	$FNAME"
echo "Last Name:	$LNAME"
echo "Company:	$COMPANY"
echo "Address:	$STREET"
echo "City:		$CITY"
echo "State:		$STATE"
echo "Zip Code:	$ZIP"
echo "Home Phone:	$HPHONE"
echo "Work Phone:	$WPHONE"
echo "Email:		$EMAIL"
echo "Website:	$WEBURL"
