#!/bin/bash
#
# Lab Objective: Make a shell script that will take two arguments; complain and exit if the first doesn't exist,
# and set a default value of 10 if the second doesn't exist.
#
# $1 is the first argument
# $2 is the second argument
#
# Note: Using string operators this script is 3 lines long including the #!/bin/bash line.

VAR1="${1?Error; an argument is not defined}"
VAR2="${2:-10}"

# See here: http://www.cyberciti.biz/tips/bash-shell-parameter-substitution-2.html
# More information: https://bash.cyberciti.biz/guide/Default_shell_variables_value
# Test lines:
echo "$VAR1"
echo "$VAR2"
