#!/bin/bash
# Fun script inspired by http://bash.im/quote/147869
# Right aligh: http://stackoverflow.com/a/4239041

# Observations - $RANDOM is not that random after all...

ASLEEP="NO"
SHEEP=0

while [ "$ASLEEP" != "YES" ]; do
    if [ $((SHEEP%20)) -eq 0 ]
      then
        echo -n "  Sheep:"; printf "%50.50s\n" "Other thoughts:"
    fi

    ((SHEEP++)); THOUGHTS=$((RANDOM%997))
    echo -n "    $SHEEP"; printf "%49.49s\n" "$THOUGHTS"

    if [ $THOUGHTS -eq 0 ]							# Chance = 1 in 997
      then
        ASLEEP="YES"
        break
      else
        sleep $(bc <<< "scale=3; $THOUGHTS / 5555")				# Randomly pause for 0.18 seconds per loop or less
    fi

    if [ $((THOUGHTS/11)) == $((RANDOM%89)) ]; then				# Chance is about 1 in 8,000 (997/11*89)
      echo "/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\\"
      echo "|     Ugh! I should calm down and fall asleep faster!!!    |"
      echo "\\~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/"
      elif [ $((THOUGHTS/7)) == $((RANDOM%139)) ]; then				# Chance is about 1 in 19,700 (997/7*139)
        echo "/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\\"
        echo "|  Man!! I REALLY must calm down and fall asleep faster!!! |"
        echo "\\~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/"
        elif [ $((THOUGHTS/3)) == $((RANDOM%331)) ]; then echo			# Chance is about 1 in 110,000 (997/3*331)
           echo "/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\\"
           echo "|     SCREW THIS!!!  Let's do something useful instead!    |"
           echo "\\~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/"
           echo; exit 123
           elif [ $((THOUGHTS/2)) == $((RANDOM%499)) ]; then clear		# Chance is about 1 in 249,000 (997/2*499)
             echo "/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\\"
             echo "|   WOW!!! Wait, what?! How many sheep? Do not recall...   |"
             echo "\\~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/"
             exec $0
    fi
done

echo "/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\\"
echo "|                      SWEET DREAMS!!!                     |"
echo "\\~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/"
