#!/bin/bash
# Fun script inspired by http://bash.im/quote/147869
# Right aligh: http://stackoverflow.com/a/4239041

ASLEEP="NO"
SHEEP=0

while [ "$ASLEEP" != "YES" ]; do
    if [ $((SHEEP%20)) -eq 0 ]
      then
        echo -n "  Sheep:"; printf "%50.50s\n" "Other thoughts:"
    fi

    THOUGHTS=$((RANDOM%999))
    if [ $THOUGHTS -eq 0 ]
      then
        ASLEEP="YES"
        break
      else
        ((SHEEP++))
        echo -n "    $SHEEP"; printf "%49.49s\n" "$THOUGHTS"
        sleep $(bc <<< "scale=3; $THOUGHTS / 5555")
    fi

    if [ $((THOUGHTS%29)) -eq 0 ]; then
        echo "/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\\"
        echo "|     Ugh! I should calm down and fall asleep faster!!!    |"
        echo "\\~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/"
        elif [ $((THOUGHTS%97)) -eq 0 ]; then
          echo "/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\\"
          echo "|  Man!! I REALLY must calm down and fall asleep faster!!! |"
          echo "\\~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/"
    fi
done
echo "Sweet dreams! :)"
